/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function add(a: number, b: number): number

export declare function cal(a: number, b: number, func: (arg0: number, arg1: number) => number): number

export declare function divide(a: number, b: number): number

export declare function heavyCalculation(n: number): number

export declare function modulo(a: number, b: number): number

export declare function multiply(a: number, b: number): number

export declare function plus100(input: number): number

export declare function subtract(a: number, b: number): number
