// Generated by Copilot
export interface TabItem {
  id: string;
  label: string;
  description?: string;
}

export interface TabsProps {
  tabs: readonly TabItem[];
  activeTab: string;
  onTabChange: (tabId: string) => void;
  children?: React.ReactNode;
}

// Re-export common types
export type { VariantProps } from "class-variance-authority";
