"use client";

import { TabsProps } from "../types";

// Generated by Copilot
export const Tabs = ({ tabs, activeTab, onTabChange, children }: TabsProps) => {
  return (
    <div>
      {/* Tab Navigation */}
      <div className="flex flex-wrap gap-2 mb-6 border-b border-gray-200">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => onTabChange(tab.id)}
            className={`px-4 py-2 text-sm font-medium rounded-t-lg transition-colors ${
              activeTab === tab.id
                ? "bg-blue-500 text-white border-b-2 border-blue-500"
                : "text-gray-600 hover:text-gray-800 hover:bg-gray-50"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Description */}
      {tabs.find((tab) => tab.id === activeTab)?.description && (
        <div className="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
          <h3 className="font-semibold text-blue-900 mb-2">
            {tabs.find((tab) => tab.id === activeTab)?.label}
          </h3>
          <p className="text-blue-800">
            {tabs.find((tab) => tab.id === activeTab)?.description}
          </p>
        </div>
      )}

      {/* Tab Content */}
      {children}
    </div>
  );
};
