#!/bin/bash

# Script to automatically update typedoc.json with generated entrypoints
# Generated by Copilot

set -euo pipefail

readonly TYPEDOC_FILE="typedoc.json"
readonly TEMP_FILE="typedoc.temp.json"

# Generate entrypoints and capture as JSON array
echo "Generating entrypoints..."
ENTRYPOINTS=$(./scripts/generate-entrypoint.sh)

# Create new typedoc.json with updated entrypoints
echo "Updating typedoc.json..."
cat > "$TEMP_FILE" << EOF
{
  "out": "docs",
  "entryPoints": $ENTRYPOINTS,
  "name": "React Design Patterns Documentation",
  "theme": "default",
  "categorizeByGroup": true,
  "sort": ["source-order"],
  "validation": {
    "notExported": true,
    "invalidLink": true,
    "notDocumented": false
  },
  "excludePrivate": true,
  "excludeProtected": false,
  "excludeInternal": false,
  "readme": "README.md",
  "includeVersion": true,
  "searchInComments": true,
  "cleanOutputDir": true,
  "titleLink": "https://github.com/weerachai06/programming-bible",
  "navigationLinks": {
    "GitHub": "https://github.com/weerachai06/programming-bible"
  },
  "githubPages": true
}
EOF

# Replace original file with updated version
mv "$TEMP_FILE" "$TYPEDOC_FILE"

echo "✅ typedoc.json updated successfully!"
echo "📖 Run 'pnpm docs:generate' to generate documentation"
