name: "[Testing] Unit Tests & Coverage"

on:
  push:
    branches: [main, develop]
    paths:
      - "nextjs/**"
      - ".github/workflows/test-coverage.yml"
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths:
      - "nextjs/**"
      - ".github/workflows/test-coverage.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: nextjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      #  การทำงานบรรทัดนี้จะช่วยให้การติดตั้ง dependencies ของ pnpm มีประสิทธิภาพมากขึ้น
      - name: Get pnpm store directory
        # ใช้ shell: bash เพื่อให้สามารถใช้คำสั่ง bash ได้
        shell: bash
        # This step captures the pnpm store path and sets it as an environment variable
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          # Use the pnpm lock file to create a unique cache key
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          # Restore keys allow fallback to previous caches if the exact key is not found
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests with coverage
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./nextjs/coverage
          flags: unitTests
