name: Deploy TypeDoc to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "nextjs/**"
      - ".github/workflows/typedoc.yml"
  pull_request:
    branches: [main]
    paths:
      - "nextjs/**"
      - ".github/workflows/typedoc.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Documentation
        run: pnpm run docs:update

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./nextjs/docs"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
